# Generated by Django 2.2.6 on 2019-10-28 22:49

from django.db import migrations, models
import django.db.models.deletion


def create_uncategorized_series(apps, schema_editor):
    # We can't import the Series model directly as it may be a newer version
    # than this migration expects. We use the historical version.
    Series = apps.get_model("goodreads", "Series")

    # Create the Uncategorized series for any Books who do not specify their
    # own series.
    uncategorized = Series(id=0, title="Uncategorized")
    uncategorized.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("role", models.CharField(max_length=64, null=True)),
                ("average_rating", models.FloatField(null=True)),
                ("ratings_count", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(null=True)),
                ("primary_work_count", models.IntegerField(null=True)),
            ],
            options={"verbose_name_plural": "Series"},
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("isbn", models.CharField(max_length=64, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("image_url", models.URLField()),
                ("num_pages", models.IntegerField(null=True)),
                ("publication_year", models.IntegerField(null=True)),
                ("publication_month", models.IntegerField(null=True)),
                ("publication_day", models.IntegerField(null=True)),
                ("average_rating", models.FloatField(null=True)),
                ("ratings_count", models.IntegerField(null=True)),
                ("sequence_number", models.IntegerField(null=True)),
                ("authors", models.ManyToManyField(to="goodreads.Author")),
                (
                    "publisher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goodreads.Publisher",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goodreads.Series",
                    ),
                ),
            ],
            options={"ordering": ("sequence_number", "title")},
        ),
        migrations.RunPython(create_uncategorized_series),
    ]
