# Generated by Django 2.2.6 on 2019-10-06 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("image_url", models.CharField(max_length=255)),
                ("published", models.DateField(null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goodreads.Author",
                    ),
                ),
            ],
        ),
    ]
