# Generated by Django 2.2.6 on 2019-10-06 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("goodreads", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={"verbose_name_plural": "Series"},
        ),
        migrations.AddField(
            model_name="book",
            name="series",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="goodreads.Series",
            ),
        ),
    ]
